services:
  omicrontestcase:
    container_name: omicrontestcase-api
    build:
      context: .
      dockerfile: OmicronTestCase/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - omicron-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: omicrontestcase-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "RuleWay123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - omicron-network

volumes:
  sql_data:

networks:
  omicron-network: